[package]
name = "tambat-ce"
version = "1.0.0"
description = "Tambat Community Edition - SSH client desktop ringan"
authors = ["CharisChakim"]
license = "MIT"
repository = "https://github.com/CharisChakim/tambat-ce"
edition = "2021"

[lib]
name = "tambat_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = "0.9"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
